#!/bin/bash

SDE_DIR=/root/sde/bf-sde-9.3.1

ps -ef | grep init_setup | grep -v grep
if [ $? -eq 0 ]; then
    killall init_setup
fi

lsmod | grep bf_knet | grep -v grep
if [ $? -eq 0 ]; then
    rmmod bf_knet
fi

lsmod | grep bf_kpkt | grep -v grep
if [ $? -eq 0 ]; then
   rmmod bf_kpkt
fi

rm -f /var/run/init_setup.file
sh $SDE_DIR/install/bin/bf_kpkt_mod_load $SDE_DIR/install/
sh $SDE_DIR/install/bin/bf_knet_mod_load $SDE_DIR/install/
cd $SDE_DIR
./run_init_setup.sh -p bgw_switch
