VPATH += $(RTE_SRCDIR)/switchbfrt

SRCS-y += bf_outer_mac_rewrite_table.c jd_bfrt.c 
SRCS-y += bf_process_protocl_packet_table.c bf_igw_ip_type_table.c
SRCS-y += bf_eip_in_jd_vxlan_table.c

CFLAGS += -I$(RTE_SRCDIR)/switchbfrt/include/ -I$(SDE_INSTALL)/include 
LDFLAGS += 
