#!/bin/bash

function perror()
{
    echo -e "$@"
    exit 0
}

function pnerror()
{
    echo -e "$@"
}

function pinfo()
{
    echo "Info: $@"
}

function check_str_null()
{
    if [ "$2" == "" ];then
        pnerror "$1"
    fi
}

function exit_str_null()
{
    if [ "$2" == "" ];then
        perror "$1"
    fi
}

DPC_CMD="/usr/local/bin/dpc stats"

function drop_pkt_monitor()
{   
    vm_host_drop_stats1=`$DPC_CMD | grep vm_host_drop_stats \
        | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $vm_host_drop_stats1
    
    nexthop_drop_stats1=`$DPC_CMD | grep nexthop_drop_stats | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $nexthop_drop_stats1

    dstip_drop_stats1=`$DPC_CMD | grep dstip_drop_stats | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $dstip_drop_stats1

    sleep 1

    vm_host_drop_stats2=`$DPC_CMD | grep vm_host_drop_stats \
        | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $vm_host_drop_stats2
    
    nexthop_drop_stats2=`$DPC_CMD | grep nexthop_drop_stats | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $nexthop_drop_stats2

    dstip_drop_stats2=`$DPC_CMD | grep dstip_drop_stats | awk -F "packets" '{print $2}' | awk -F "=" '{print $2}' | awk -F "," '{print $1}'`
    exit_str_null "droppkt_state:0, desc: no drop_pkt" $dstip_drop_stats2

    if [ "$vm_host_drop_stats2" -gt "$vm_host_drop_stats1" ];then
         echo "droppkt_state:255, desc: igw have no vm location dorp!"
         exit 0
    fi
    
    if [ "$nexthop_drop_stats2" -gt "$nexthop_drop_stats1" ];then
         echo "droppkt_state:255, desc: igw have nexthop_drop!"
         exit 0
    fi
    
    if [ "$dstip_drop_stats2" -gt "$dstip_drop_stats1" ];then
	    echo "droppkt_state:255, desc: igw have dstip_drop!"
	    exit 0
    fi
}

function main()
{
    drop_pkt_monitor
    echo "droppkt_state:0, desc: no drop_pkt"
}

main
