#!/bin/bash

RED='\e[1;31m'
NC='\e[0m'

function perror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
    exit 1
}

function pnerror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
}

function pinfo()
{
    echo "Info: $@"
}

function check_str_null()
{
    if [ "$2" == "" ];then
        pnerror "$1"
    fi
}

function exit_str_null()
{
    if [ "$2" == "" ];then
        perror "$1"
    fi
}

function get_all_hbgw_gw_ip()
{
    cat /etc/hostif.json | grep gw_ip | awk -F '"' '{print $4}' > tmpgwip.file
    mapfile HBGW_GW_IPS < tmpgwip.file
}

function ping_hbgw_gwip()
{
    for key in ${!HBGW_GW_IPS[@]}
    do
        ping -c 1 ${HBGW_GW_IPS[$key]} > /dev/null
        if [ $?  -eq 0 ]; then
            pinfo "ping ${HBGW_GW_IPS[$key]} success!"
        else
            pnerror "ping ${HBGW_GW_IPS[$key]} fail!"   
        fi
    done
}

function show_bgp_route()
{
    vtysh -c "show ip route bgp"
}   

function check_lo_up()
{
    LO_STATE=`ifconfig|grep -E 'lo' | grep UP`
    exit_str_null "lo is down or not found!" $LO_STATE
}   

function check_lo_vip()
{
    VIP=`cat /etc/hostif.json | grep vip | awk -F '"' 'NR==1{print $4}'`
    check_lo_vip=`ip addr show dev lo | grep $VIP`
    exit_str_null "lo VIP is not found!" $check_lo_vip
} 

function check_default_route()
{
    DEV=`ip route | grep default | awk -F " " 'NR==1{print $5}'`
    if [ "$DEV" == "ma1" ];then
        perror "default route via ma1"
    fi
} 

function check_bgp_cfg()
{
    bgp_peer_num=`vtysh -c "show run" | grep neighbor | grep remote-as | wc -l`
    echo "bgp_peer_num is $bgp_peer_num"
    host_if_num=`cat /etc/hostif.json  | grep Ethernet | wc -l`
    echo "host_if_num is $host_if_num"
    if [ "$bgp_peer_num" != "$host_if_num" ];then
        perror "bgp_peer_num is neq host_if_num"
    fi
    
    network_num=` vtysh -c "show run" | grep network | wc -l`
    tmp_num0=`expr $network_num - 1`
 
    match_prefixlist_num=`vtysh -c "show run" | grep "prefix-list" | grep match | wc -l`
    if [ "$bgp_peer_num" != "$match_prefixlist_num" ];then
        perror "bgp_peer_num is neq host_if_num"
    fi

    neighbor_routemap_num=`vtysh -c "show run" | grep route-map | grep neighbor | wc -l` 
    tmp_num1=`expr 2 \* $match_prefixlist_num`
    if [ "$neighbor_routemap_num" != "$tmp_num1" ];then
        perror "neighbor_routemap_num is wrong"
    fi

    routemap_permit_num=`vtysh -c "show run" | grep route-map | grep permit | wc -l` 
    tmp_num2=`expr 2 \* $match_prefixlist_num`
    if [ "$routemap_permit_num" != "$tmp_num2" ];then
        perror "routemap_permit_num is wrong"
    fi

    ip_prefixlist_num=`vtysh -c "show run" | grep "ip prefix-list" | wc -l` 
    tmp_num3=`expr 3 \* $match_prefixlist_num`
    if [ "$ip_prefixlist_num" != "$tmp_num3" ];then
        perror "ip_prefixlist_num is wrong"
    fi
} 

function check_bgp_state()
{
    bgp_peer_num=`vtysh -c "show run" | grep neighbor | grep remote-as | wc -l`
    bgp_Established_num=`vtysh -c "show bgp neighbors "  | grep Established | wc -l`
    if [ "$bgp_peer_num" != "$bgp_Established_num" ];then
        perror "bgp_peer_num is neq bgp_Established_num"
    fi
    
    Hold_time=`vtysh -c "show bgp neighbors "  | grep  "Hold time" | awk -F " " '{print $4}' | awk -F "," 'NR==1{print $1}'`
    if [ "$Hold_time" != 15 ];then
        perror "Hold_time is neq 15"
    fi

    keepalive_time=`vtysh -c "show bgp neighbors "  | grep  "Hold time" | awk -F " " '{print $8}' | awk -F "," 'NR==1{print $1}'`
    if [ "$keepalive_time" != 5 ];then
        perror "keepalive_time is neq 5"
    fi
}

function check_rc_local()
{
    RC_LOCAL=`cat /etc/rc.local | grep "service frr stop" | grep -v "#"`
    exit_str_null "service frr stop is not found in /etc/rc.local!" $RC_LOCAL
}   

function check_bgpd()
{
    BGPD=`ps -ef | grep frr | grep bgpd`
    exit_str_null "bgpd not found " $BGPD
}   

function check_cron_and_syslog()
{
    CROND=`ps -ef | grep cron | grep sbin`
    exit_str_null "cron not found " $CROND
    SYSLOGD=`ps -ef | grep rsyslogd | grep sbin`
    exit_str_null "rsyslogd not found " $SYSLOGD
}

function main()
{
    echo "--------------Test ping hbgw gw ip---------------"
    get_all_hbgw_gw_ip
    ping_hbgw_gwip
        
    echo "--------------Test lo state ---------------"
    check_lo_up
    check_lo_vip
    echo "lo is up and vip is ok"

    echo "--------------Test rc.local and cron---------------"
    check_rc_local
    check_cron_and_syslog

    echo "--------------Test frr show running-config---------------"
    check_bgpd
    check_bgp_cfg
    
    echo "--------------Test bgp state---------------"
    check_bgp_state
    
    echo "--------------Test default route ---------------"
    check_default_route
    echo "default_route is bgp route"
}

main
