#!/bin/bash

RED='\e[1;31m'
NC='\e[0m'

function perror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
    exit 1
}

function pnerror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
}

function pinfo()
{
    echo "Info: $@"
}

function check_str_null()
{
    if [ "$2" == "" ];then
        pnerror "$1"
    fi
}

function exit_str_null()
{
    if [ "$2" == "" ];then
        perror "$1"
    fi
}

function get_all_higw_ipv4gw_ip()
{
    cat /etc/hostif.json | grep gw_ip | awk -F '"' '{print $4}' > tmpgwip.file
    mapfile HIGW_V4GW_IPS < tmpgwip.file
}

function get_all_higw_ipv6gw_ip()
{
    cat /etc/hostif.json | grep gw6_ip | awk -F '"' '{print $4}' > tmpv6gwip.file
    mapfile HIGW_V6GW_IPS < tmpv6gwip.file
}

function ping_higw_ipv4gwip()
{
    for key in ${!HIGW_V4GW_IPS[@]}
    do
        ping -c 1 ${HIGW_V4GW_IPS[$key]} > /dev/null
        if [ $?  -eq 0 ]; then
            pinfo "ping ${HIGW_V4GW_IPS[$key]} success!"
        else
            pnerror "ping ${HIGW_V4GW_IPS[$key]} fail!"   
        fi
    done
}

function ping_higw_ipv6gwip()
{
    for key in ${!HIGW_V6GW_IPS[@]}
    do
        ping -c 1 ${HIGW_V6GW_IPS[$key]} > /dev/null
        if [ $?  -eq 0 ]; then
            pinfo "ping ${HIGW_V6GW_IPS[$key]} success!"
        else
            pnerror "ping ${HIGW_V6GW_IPS[$key]} fail!"   
        fi
    done
}

function show_bgp_route()
{
    vtysh -c "show ip route bgp"
}   

function check_lo_up()
{
    LO_STATE=`ifconfig|grep -E 'lo' | grep UP`
    exit_str_null "lo is down or not found!" $LO_STATE
}   

function check_lo_vip()
{
    VIP=`cat /etc/hostif.json | grep vip | awk -F '"' 'NR==1{print $4}'`
    check_lo_vip=`ip addr show dev lo | grep $VIP`
    exit_str_null "lo VIP is not found!" $check_lo_vip
} 

function check_default_route()
{
    DEV=`ip route | grep default | awk -F " " 'NR==1{print $5}'`
    if [ "$DEV" == "ma1" ];then
        perror "default route via ma1"
    fi
} 

function check_bgp_cfg()
{
    bgp_peer_num=`vtysh -c "show run" | grep  peer-group | grep ipv6-lsw  | wc -l`
    bgp_peer_num=$((bgp_peer_num - 1))
    echo "ipv4 bgp_peer_num is $bgp_peer_num"
    host_if_num=`cat /etc/hostif.json  | grep Ethernet | wc -l`
    echo "host_if_num is $host_if_num"
    if [ "$bgp_peer_num" != "$host_if_num" ];then
        perror "bgp_peer_num is neq host_if_num"
    fi
} 

function check_lsw1_cfg()
{
    first_hop=""
    echo "Check the wiring of the lsw1"
    
    ip_list=$(vtysh -c "show run" | grep "peer-group lsw1" | awk -F " " '{print $2}')
    ip_array=()

    for ip in $ip_list; do
        ip_array+=("$ip")
    done

    for ip in "${ip_array[@]}"
    do
        echo "Traceroute $ip ..."
        hop=$(traceroute -n  -m 2 "$ip" | grep ms  | awk  -F " " '{print $2}')
        
        while [ "$hop" = "*" ]; do
            sleep 1  
            hop=$(traceroute -n  -m 2 "$ip" | grep ms  | awk  -F " " '{print $2}')
        done
        
        if [ -z "$first_hop" ]; then
            first_hop="$hop"
            echo "First hop: $first_hop"
        elif [ "$first_hop" != "$hop" ]; then
            perror "First hop is different: $hop"
        else
            echo "First hop is the same: $hop"
        fi
    done
    echo "lsw1 is ok"
}

function check_lsw2_cfg()
{
    first_hop=""
    echo "Check the wiring of the lsw2"
    
    ip_list=$(vtysh -c "show run" | grep "peer-group lsw2" | awk -F " " '{print $2}')
    ip_array=()

    for ip in $ip_list; do
        ip_array+=("$ip")
    done

    for ip in "${ip_array[@]}"
    do
        echo "Traceroute $ip ..."
        hop=$(traceroute -n  -m 2 "$ip" | grep ms  | awk  -F " " '{print $2}')
    
        while [ "$hop" = "*" ]; do
            sleep 1  
            hop=$(traceroute -n  -m 2 "$ip" | grep ms  | awk  -F " " '{print $2}')
        done

        if [ -z "$first_hop" ]; then
            first_hop="$hop"
            echo "First hop: $first_hop"
        elif [ "$first_hop" != "$hop" ]; then
            perror "First hop is different: $hop"
        else
            echo "First hop is the same: $hop"
        fi
    done
    echo "lsw2 is ok"
}

function check_bgp_state()
{
    bgp_peer_num=`vtysh -c "show run" | grep  peer-group | grep ipv6-lsw  | wc -l`
    bgp_peer_num=$((bgp_peer_num - 1))
    bgp_peer_num=$((bgp_peer_num * 2 ))

    bgp_Established_num=`vtysh -c "show bgp neighbors "  | grep Established | wc -l`
    if [ "$bgp_peer_num" != "$bgp_Established_num" ];then
        perror "bgp_peer_num is neq bgp_Established_num"
    fi
    echo "bgp_Established_num is $bgp_Established_num"
    echo "v4 and v6 bgp_peer_num is $bgp_peer_num"

    Hold_time=`vtysh -c "show bgp neighbors "  | grep  "Hold time" | awk -F " " '{print $4}' | awk -F "," 'NR==1{print $1}'`
    if [ "$Hold_time" != 15 ];then
        perror "Hold_time is neq 15"
    fi

    keepalive_time=`vtysh -c "show bgp neighbors "  | grep  "Hold time" | awk -F " " '{print $8}' | awk -F "," 'NR==1{print $1}'`
    if [ "$keepalive_time" != 5 ];then
        perror "keepalive_time is neq 5"
    fi
}

function check_rc_local()
{
    RC_LOCAL=`cat /etc/rc.local | grep "service frr stop" | grep -v "#"`
    exit_str_null "service frr stop is not found in /etc/rc.local!" $RC_LOCAL
}   

function check_bgpd()
{
    BGPD=`ps -ef | grep frr | grep bgpd`
    exit_str_null "bgpd not found " $BGPD
}   

function check_cron_and_syslog()
{
    CROND=`ps -ef | grep cron | grep sbin`
    exit_str_null "cron not found " $CROND
    SYSLOGD=`ps -ef | grep rsyslogd | grep sbin`
    exit_str_null "rsyslogd not found " $SYSLOGD
}

function main()
{
    echo "--------------Test ping higw gw ip---------------"
    get_all_higw_ipv4gw_ip
    ping_higw_ipv4gwip
    get_all_higw_ipv6gw_ip
    ping_higw_ipv6gwip
        
    echo "--------------Test lo state ---------------"
    check_lo_up
    check_lo_vip
    echo "lo is up and vip is ok"

    echo "--------------Test rc.local and cron---------------"
    check_rc_local
    check_cron_and_syslog

    echo "--------------Test frr show running-config---------------"
    check_bgpd
    check_bgp_cfg
    
    echo "--------------Test lsw line config---------------"
    check_lsw1_cfg
    check_lsw2_cfg
    
    echo "--------------Test bgp state---------------"
    check_bgp_state

    echo "--------------Test default route ---------------"
    check_default_route
    echo "default_route is bgp route"
}

main


