#!/bin/bash

RED='\e[1;31m'
NC='\e[0m'

function perror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
    exit 1
}

function pnerror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
}

function pinfo()
{
    echo "Info: $@"
}

function check_str_null()
{
    if [ "$2" == "" ];then
        pnerror "$1"
    fi
}

function exit_str_null()
{
    if [ "$2" == "" ];then
        perror "$1"
    fi
}

function safe_check()
{
    if [ -f "/etc/frr/frr.conf" ];then
        perror "please backup /etc/frr/frr.conf and delete it"
    fi
}

HOSTIF_CFG_FILE=/etc/hostif.json

function get_bgp_info()
{
    L_AS_NUM=`cat $HOSTIF_CFG_FILE | grep local_as_num | awk -F '"' '{print $4}'`
    exit_str_null "local_as_num is not found in hostif.json!" $L_AS_NUM
    R_AS_NUM=`cat $HOSTIF_CFG_FILE | grep remote_as_num | awk -F '"' '{print $4}'`
    exit_str_null "remote_as_num is not found in hostif.json!" $L_AS_NUM
    ROUTER_ID=`ifconfig ma1 | grep inet | grep -v inet6 | awk -F ' ' '{print $2}'`
    exit_str_null "ma1 ipv4 addr is not found!" $ROUTER_ID
}

function get_ip()
{
    VIP=`cat $HOSTIF_CFG_FILE | grep vip | grep -v backup_vip | awk -F '"' '{print $4}'`
    exit_str_null "vip is not found!" $VIP
    MIP=`cat $HOSTIF_CFG_FILE | grep mgt_ip | awk -F '"' '{print $4}'`
    exit_str_null "mgt_ip is not found!" $MIP
}

function create_router_id
{
    CMD=`vtysh -c "config" -c "router bgp $L_AS_NUM" -c "bgp router-id $ROUTER_ID" -c "exit" -c "exit"`
    if [ "$?" != "0" ];then
        perror "rebuild_router_id fail"
    fi
}

function create_neighbor()
{
    CMD=`vtysh -c "config" -c "router bgp $L_AS_NUM" -c "neighbor $NEI_IP remote-as $R_AS_NUM" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_neighbor fail"
    fi
    CMD=`vtysh -c "config" -c "router bgp $L_AS_NUM" -c "neighbor $NEI_IP update-source $IP" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_neighbor fail"
    fi
    echo "create_neighbor ok for $HOSTIF_NAME"
}

function create_ip_prefixlist()
{
    CMD=`vtysh  -c "config" -c "ip prefix-list prefixl-$HOSTIF_NAME seq 5 permit $VIP/32" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_ip_prefixlist fail"
    fi
      
    CMD=`vtysh  -c "config" -c "ip prefix-list prefixl-$HOSTIF_NAME seq 10 permit $MIP/32" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_ip_prefixlist fail"
    fi    

    CMD=`vtysh  -c "config" -c "ip prefix-list prefixl-$HOSTIF_NAME seq 15 permit $IP/32" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_ip_prefixlist fail"
    fi
    echo "create_ip_prefixlist ok for $HOSTIF_NAME"
}

function create_router_map()
{
    CMD=`vtysh  -c "config" -c "route-map rp-out-$HOSTIF_NAME permit 10" -c "match ip address prefix-list prefixl-$HOSTIF_NAME " -c "exit" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_router_map fail"
    fi
    CMD=`vtysh  -c "config" -c "route-map rp-in-$HOSTIF_NAME permit 10" -c "exit" -c "exit"`
    if [ "$?" != "0" ];then
        perror "create_router_map fail"
    fi
    echo "create_router_map ok for $HOSTIF_NAME"
}

function bound_router_map()
{
    CMD=`vtysh  -c "config" -c "router bgp $L_AS_NUM" -c "address-family ipv4 unicast" -c "neighbor $NEI_IP soft-reconfiguration inbound" -c "exit"`
    if [ "$?" != "0" ];then
        perror "bound_router_map fail"
    fi
    CMD=`vtysh  -c "config" -c "router bgp $L_AS_NUM" -c "address-family ipv4 unicast" -c "neighbor $NEI_IP route-map rp-out-$HOSTIF_NAME out" -c "exit"`
    if [ "$?" != "0" ];then
        perror "bound_router_map fail"
    fi
    CMD=`vtysh  -c "config" -c "router bgp $L_AS_NUM" -c "address-family ipv4 unicast" -c "neighbor $NEI_IP route-map rp-in-$HOSTIF_NAME in" -c "exit"`
    if [ "$?" != "0" ];then
        perror "bound_router_map fail"
    fi
    echo "bound_router_map ok for $HOSTIF_NAME"
}

function network_ip()
{
    CMD=`vtysh  -c "config" -c "router bgp $L_AS_NUM" -c "network $IP/32" -c "exit"`
    if [ "$?" != "0" ];then
        perror "network_ip fail"
    fi
    echo "network_ip ok for $HOSTIF_NAME"
}

function write_file()
{
    vtysh  -c "write" -c "exit"
}

function rebuild_bgp_conf
{   
    peers=`cat $HOSTIF_CFG_FILE | grep intf_name | wc -l`
    for ((i=1; i<=peers; i++))
    do
        IP=`cat $HOSTIF_CFG_FILE | grep ip | grep -v mgt_ip | grep -v vip | grep -v gw_ip | awk -F '"' '{print $4}' | sed -n "${i}p"`
        exit_str_null "IP is not found!" $IP
        NEI_IP=`cat $HOSTIF_CFG_FILE | grep gw_ip | awk -F '"' '{print $4}' | sed -n "${i}p"`
        exit_str_null "NEI_IP is not found!" $NEI_IP
        HOSTIF_NAME=`cat $HOSTIF_CFG_FILE | grep intf_name | awk -F '"' '{print $4}' | sed -n "${i}p"`
        exit_str_null "HOSTIF_NAME is not found!" $HOSTIF_NAME

        create_neighbor
        create_ip_prefixlist
        create_router_map
        bound_router_map
    done
}

function main()
{
    safe_check 
    get_bgp_info
    get_ip
    create_router_id
    rebuild_bgp_conf
    write_file
}

main
