#!/bin/bash

RED='\e[1;31m'
NC='\e[0m'

function perror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
    exit 1
}

function pnerror()
{
    echo -e "${RED} ===============================Error=================================== ${NC}"
    echo -e "${RED} Error: $@ ${NC}"
}

function pinfo()
{
    echo "Info: $@"
}

function check_str_null()
{
    if [ "$2" == "" ];then
        pnerror "$1"
    fi
}

function exit_str_null()
{
    if [ "$2" == "" ];then
        perror "$1"
    fi
}

function get_gw_ip()
{
    IP=`ifconfig -a $HOSTIF | grep inet | grep -v inet6 | awk -F ' ' '{print $2}'`
    exit_str_null "$HOSTIF is not found or no ip!" $IP
    IP_CHECK=`cat /etc/hostif.json | grep $IP`
    exit_str_null "hostif ip is not fount in /etc/hostif.json!" $IP_CHECK
    GW_IP=`cat /etc/hostif.json | grep $HOSTIF -A3 | grep gw_ip | awk -F '"' '{print $4}'`
    exit_str_null "gw_ip is not found !" $GW_IP
    SHUTDOWN_BGP_PEER="no neighbor $GW_IP shutdown"
}

function if_up_hosit()
{
    ifconfig $HOSTIF up
    echo "ifconfig $HOSTIF up"
}

function get_router_bgp_as_num()
{
    ROUTE_BGP_AS=`cat /etc/frr/frr.conf  | grep "router bgp"`
    exit_str_null "router bgp as-number is not found!" $ROUTE_BGP_AS
}

function no_shutdown_bgp_peer()
{
  CMD=`vtysh  -c "configure" -c "$ROUTE_BGP_AS"  -c "$SHUTDOWN_BGP_PEER"  -c "exit" -c "exit" -c "exit"`
  if [ "$?" != "0" ];then
        perror "no shutdown bgp peer fail"
  fi
  echo "no shutdown bgp peer $GW_IP ok"
}

function main()
{
    get_gw_ip 
    get_router_bgp_as_num
    no_shutdown_bgp_peer
    if_up_hosit
}

if [ $# != 1 ];then
    perror "$0 Ethernetxx #e.g: $0 Ethernet17"
fi
HOSTIF=$1

main
