frr version 8.1
frr defaults traditional
hostname localhost
log syslog informational
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65002
 bgp router-id 5.5.5.5
 neighbor 100.125.50.5 remote-as 65303
 neighbor 100.125.50.5 update-source 100.125.50.4
 neighbor 100.125.50.7 remote-as 65303
 neighbor 100.125.50.7 update-source 100.125.50.6
 neighbor 100.125.51.5 remote-as 65303
 neighbor 100.125.51.5 update-source 100.125.51.4
 neighbor 100.125.51.7 remote-as 65303
 neighbor 100.125.51.7 update-source 100.125.51.6
 !
 address-family ipv4 unicast
  network 10.226.190.100/32
  network 10.226.190.236/32
  neighbor 100.125.50.5 soft-reconfiguration inbound
  neighbor 100.125.50.5 route-map rp-eth17-in in
  neighbor 100.125.50.5 route-map rp-eth17 out
  neighbor 100.125.50.7 soft-reconfiguration inbound
  neighbor 100.125.50.7 route-map rp-eth18-in in
  neighbor 100.125.50.7 route-map rp-eth18 out
  neighbor 100.125.51.5 soft-reconfiguration inbound
  neighbor 100.125.51.5 route-map rp-eth21-in in
  neighbor 100.125.51.5 route-map rp-eth21 out
  neighbor 100.125.51.7 soft-reconfiguration inbound
  neighbor 100.125.51.7 route-map rp-eth22-in in
  neighbor 100.125.51.7 route-map rp-eth22 out
 exit-address-family
exit
!
ip prefix-list addr18 seq 5 permit 10.226.190.100/32
ip prefix-list addr18 seq 10 permit 10.226.190.236/32
ip prefix-list addr17 seq 5 permit 10.226.190.100/32
ip prefix-list addr17 seq 10 permit 10.226.190.236/32
ip prefix-list addr21 seq 5 permit 10.226.190.100/32
ip prefix-list addr21 seq 10 permit 10.226.190.236/32
ip prefix-list addr22 seq 5 permit 10.226.190.100/32
ip prefix-list addr22 seq 10 permit 10.226.190.236/32
!
route-map rp-eth17 permit 10
 match ip address prefix-list addr17
exit
!
route-map rp-eth18 permit 10
 match ip address prefix-list addr18
exit
!
route-map rp-eth17-in permit 10
exit
!
route-map rp-eth18-in permit 10
exit
!
route-map rp-eth21 permit 10
 match ip address prefix-list addr21
exit
!
route-map rp-eth22 permit 10
 match ip address prefix-list addr22
exit
!
route-map rp-eth21-in permit 10
exit
!
route-map rp-eth22-in permit 10
exit
!
