frr version 8.1
frr defaults traditional
hostname localhost
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65002
 bgp router-id 10.226.137.238
 no bgp network import-check
 neighbor ipv6-lsw peer-group
 neighbor ipv6-lsw remote-as 65303
 neighbor lsw1 peer-group
 neighbor lsw1 remote-as 65303
 neighbor lsw2 peer-group
 neighbor lsw2 remote-as 65303
 neighbor fc00:a:2554:4000:c802:1c8:b01:100 peer-group ipv6-lsw
 neighbor fc00:a:2554:4000:c802:1c8:b01:200 peer-group ipv6-lsw
 neighbor fc00:a:2554:4000:c802:2c8:b01:100 peer-group ipv6-lsw
 neighbor fc00:a:2554:4000:c802:2c8:b01:200 peer-group ipv6-lsw
 neighbor 100.125.50.9 peer-group lsw1
 neighbor 100.125.50.11 peer-group lsw1
 neighbor 100.125.51.9 peer-group lsw2
 neighbor 100.125.51.11 peer-group lsw2
 !
 address-family ipv4 unicast
  network 10.226.190.102/32
  network 10.226.190.103/32 route-map additive_6_as_path
  network 10.226.190.104/32 route-map additive_3_as_path
  network 10.226.190.105/32
  network 10.226.190.106/32
  network 10.226.190.107/32
  network 10.226.190.108/32
  network 10.226.190.109/32
  network 10.226.190.110/32
  network 10.226.190.111/32
  neighbor lsw1 soft-reconfiguration inbound
  neighbor lsw1 route-map rp-in-lsw1 in
  neighbor lsw1 route-map rp-out-lsw1 out
  neighbor lsw2 soft-reconfiguration inbound
  neighbor lsw2 route-map rp-in-lsw2 in
  neighbor lsw2 route-map rp-out-lsw2 out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2403:1ec0:954c:8011::/64 route-map additive_6_as_path
  neighbor ipv6-lsw activate
  neighbor ipv6-lsw soft-reconfiguration inbound
  neighbor ipv6-lsw route-map rp-in-ipv6-lsw in
  neighbor ipv6-lsw route-map rp-out-ipv6-lsw out
 exit-address-family
exit
!
ip prefix-list lsw2-dlip-prefix seq 5 permit 20.20.20.0/24
ip prefix-list lsw1-dlip-prefix seq 5 permit 20.20.20.0/25
!
route-map additive_6_as_path permit 10
 set as-path prepend 65002 65002 65002 65002 65002 65002
exit
!
route-map additive_3_as_path permit 10
 set as-path prepend 65002 65002 65002
exit
!
route-map rp-in-lsw1 permit 10
exit
!
route-map rp-out-lsw1 deny 10
 match ip address prefix-list lsw2-dlip-prefix
exit
!
route-map rp-out-lsw1 permit 1000
exit
!
route-map rp-in-lsw2 permit 10
exit
!
route-map rp-out-lsw2 deny 10
 match ip address prefix-list lsw1-dlip-prefix
exit
!
route-map rp-out-lsw2 permit 1000
exit
!
route-map rp-in-ipv6-lsw permit 10
exit
!
route-map rp-out-ipv6-lsw permit 10
exit
!
